#!/bin/bash
#
# chkconfig: 2345 50 50

### BEGIN INIT INFO
# Provides: bosh_agent
# Required-Start: $network $local_fs
# Required-Stop: $network $local_fs
# Should-Start: $syslog $named ntpdate
# Should-Stop: $syslog $named
# Short-Description: start and stop bosh agent
# Description: BOSH agent
### END INIT INFO

# Source function library.
. /etc/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

prog=bosh_agent
lockfile=/var/lock/subsys/$prog
export PATH=/var/vcap/bosh/bin:$PATH

start() {
		# Start daemons.
		echo -n $"Starting $prog: "
		/var/vcap/bosh/bin/bosh_agent -c -P centos -I $(cat /etc/infrastructure) 2>&1 > /var/vcap/bosh/log/agent.log &
		echo
	touch $lockfile
	return 0
}

stop() {
	[ "$EUID" != "0" ] && exit 4
		echo -n $"Shutting down $prog: "
	killproc $prog
	RETVAL=$?
		echo
	[ $RETVAL -eq 0 ] && rm -f $lockfile
	return $RETVAL
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status $prog
	;;
  restart|force-reload)
	stop
	start
	;;
  try-restart|condrestart)
	if status $prog > /dev/null; then
		stop
		start
	fi
	;;
  reload)
	exit 3
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|try-restart|force-reload}"
	exit 2
esac